puts "Testing all escape char"
puts "this is \\a \a NEXT"
puts "this is \\b \b NEXT"
puts "this is \\f \f NEXT"
puts "this is \\n \n NEXT"
puts "this is \\r \r NEXT"
puts "this is \\uFF100A \FF100A NEXT"
puts "this is \\v \v NEXT"
puts "this is \\x12 \x12 NEXT"
